# Generated by Django 5.2.5 on 2025-08-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameIndex(
            model_name='attempt',
            new_name='quiz_attemp_quiz_id_9e84ee_idx',
            old_name='quiz_attemp_quiz_id_4721c6_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='quiz_quiz_course__ef5819_idx',
            old_name='quiz_quiz_course__76ca5e_idx',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='strategy',
            field=models.CharField(choices=[('fixed', 'fixed'), ('adaptive', 'adaptive')], default='fixed', max_length=16),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
