# Generated by Django 5.2.5 on 2025-08-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='ability_estimate',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='min_questions',
            field=models.PositiveIntegerField(blank=True, default=6, null=True),
        ),
    ]
